# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftTemplate
    pod 'SnapKit', '~> 5.0.0'

  target 'SwiftTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftTemplateUITests' do
    # Pods for testing
  end

end
